name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - Branch4-Course-About-Services-Done
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - Branch4-Course-About-Services-Done

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Dependencies & Build
        run: |
          npm ci
          npm run build

      - name: Build And Deploy to Azure
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "dist/maharishi-kapi/browser"
          api_location: ""
<<<<<<< HEAD
          skip_app_build: true
=======
          skip_app_build: true
>>>>>>> 9146571 (Gitflow-andDownload-Removed)
